springdoc:
  api-docs:
    path: /open-api/json      # OpenAPI 文档 JSON
  swagger-ui:
    path: /open-api/html      # Swagger UI HTML
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

server:
  port: 7456